#
# This file is autogenerated during plugin quickstart and overwritten during
# plugin makedist. DO NOT CHANGE IT if you plan to use plugin makedist to update 
# the distribution.
#
from setuptools import setup, find_packages
from pip.req import parse_requirements

# parse_requirements() returns generator of pip.req.InstallRequirement objects
install_reqs = parse_requirements('requirements.txt')
reqs = [str(ir.req) for ir in install_reqs]

kwargs = {'author': 'Pierre-Elouan Rethore',
 'author_email': 'pire@dtu.dk',
 'classifiers': ['Intended Audience :: Science/Research',
                 'Topic :: Scientific/Engineering'],
 'description': 'A wind plant layout optimization tool',
 'download_url': 'https://github.com/DTUWindEnergy/TOPFARM.git',
 'include_package_data': True,
 'install_requires': ['openmdao.main'],
 'keywords': ['openmdao'],
 'license': 'AGPL v3.0',
 'maintainer': 'Pierre-Elouan Rethore',
 'maintainer_email': 'pire@dtu.dk',
 'name': 'topfarm',
 'package_data': {'topfarm': []},
 'package_dir': {'': 'src'},
 'packages': ['topfarm'],
 'install_requires': reqs,
 'version': '0.1.0',
 'zip_safe': False}


setup(**kwargs)

